/** Miasta do wnioskowania ISO z `adr_Miejscowosc` — tylko nazwy jednoznaczne. */

export const IVOCLAR_CITIES_BY_COUNTRY: Record<string, readonly string[]> = {
  PL: [
    "Warszawa", "Kraków", "Krakow", "Łódź", "Lodz", "Wrocław", "Wroclaw", "Poznań",
    "Poznan", "Gdańsk", "Gdansk", "Szczecin", "Bydgoszcz", "Lublin", "Białystok",
    "Bialystok", "Katowice", "Gdynia", "Częstochowa", "Czestochowa", "Radom",
    "Sosnowiec", "Toruń", "Torun", "Kielce", "Rzeszów", "Rzeszow", "Gliwice",
    "Zabrze", "Olsztyn", "Bielsko-Biała", "Bielsko-Biala", "Bytom", "Rybnik",
    "Ruda Śląska", "Ruda Slaska", "Tychy", "Opole", "Elbląg", "Elblag", "Płock",
    "Plock", "Wałbrzych", "Walbrzych", "Włocławek", "Wloclawek", "Tarnów", "Tarnow",
    "Chorzów", "Chorzow", "Koszalin", "Kalisz", "Legnica", "Grudziądz", "Grudziadz",
    "Słupsk", "Slupsk", "Jaworzno", "Jastrzębie-Zdrój", "Nowy Sącz", "Jelenia Góra",
    "Siedlce", "Mysłowice", "Konin", "Piła", "Pila", "Ostrołęka", "Ostroleka",
    "Łomża", "Lomza", "Suwałki", "Suwalki", "Gorzów", "Gorzow",
    "Zielona Góra", "Zielona Gora", "Leszno", "Ostrów Wielkopolski", "Gniezno",
    "Stargard", "Świnoujście", "Tczew", "Wejherowo", "Pruszków", "Pruszkow",
    "Legionowo", "Otwock", "Piaseczno", "Wołomin", "Zgierz", "Pabianice",
    "Bełchatów", "Piotrków Trybunalski", "Radomsko", "Skarżysko-Kamienna",
    "Starachowice", "Ostrowiec Świętokrzyski", "Mielec", "Dębica", "Tarnobrzeg",
    "Przemyśl", "Krosno", "Sanok", "Jarosław", "Chełm", "Zamość", "Biała Podlaska",
    "Puławy", "Kraśnik", "Łuków", "Ełk", "Elk", "Iława", "Ostróda", "Giżycko",
    "Kętrzyn", "Szczytno", "Mrągowo", "Piecki", "Krzeszowice", "Pniewy", "Chodzież",
    "Chodziez", "Wymysłów", "Wymyslow", "Łask", "Lask", "Września", "Wrzesnia",
  ],
  DE: [
    "Berlin", "Hamburg", "München", "Munchen", "Munich", "Köln", "Koln", "Cologne",
    "Frankfurt", "Stuttgart", "Düsseldorf", "Dusseldorf", "Dortmund", "Essen",
    "Leipzig", "Bremen", "Dresden", "Hannover", "Nürnberg", "Nurnberg", "Duisburg",
    "Bochum", "Wuppertal", "Bielefeld", "Bonn", "Münster", "Munster", "Karlsruhe",
    "Mannheim", "Augsburg", "Wiesbaden", "Gelsenkirchen", "Mönchengladbach",
    "Braunschweig", "Chemnitz", "Kiel", "Aachen", "Halle", "Magdeburg", "Freiburg",
    "Krefeld", "Mainz", "Lübeck", "Lubeck", "Erfurt", "Rostock", "Kassel", "Hagen",
    "Hamm", "Saarbrücken", "Saarbrucken", "Potsdam", "Ludwigshafen", "Oldenburg",
    "Osnabrück", "Osnabruck", "Leverkusen", "Heidelberg", "Darmstadt", "Regensburg",
    "Würzburg", "Wurzburg", "Göttingen", "Gottingen", "Heilbronn", "Ulm", "Paderborn",
    "Recklinghausen", "Ingolstadt", "Wolfsburg", "Offenbach", "Bottrop",
    "Bremerhaven", "Reutlingen", "Koblenz", "Bergisch Gladbach", "Jena", "Erlangen",
    "Trier", "Kaiserslautern", "Schwerin", "Gütersloh", "Iserlohn", "Zwickau",
    "Düren", "Ratingen", "Lünen", "Marl", "Velbert", "Minden", "Norderstedt",
    "Bamberg", "Bayreuth", "Passau", "Rosenheim", "Landshut", "Konstanz", "Flensburg",
    "Wilhelmshaven", "Cottbus", "Siegen", "Gera", "Hildesheim", "Hanau", "Detmold",
  ],
  CZ: [
    "Praha", "Prague", "Brno", "Ostrava", "Plzeň", "Plzen", "Liberec", "Olomouc",
    "České Budějovice", "Ceske Budejovice", "Hradec Králové", "Hradec Kralove",
    "Ústí nad Labem", "Usti nad Labem", "Pardubice", "Zlín", "Zlin", "Jihlava",
    "Havířov", "Havirov", "Kladno", "Most", "Opava", "Frýdek-Místek", "Frydek-Mistek",
    "Karviná", "Karvina", "Teplice", "Děčín", "Decin", "Karlovy Vary", "Jablonec",
    "Mladá Boleslav", "Mlada Boleslav", "Prostějov", "Prostejov", "Přerov", "Prerov",
    "Třebíč", "Trebic", "Znojmo", "Tábor", "Tabor", "Příbram", "Pribram", "Cheb",
    "Trutnov", "Orlová", "Orlova", "Nový Jičín", "Novy Jicin", "Česká Lípa",
    "Kroměříž", "Kromeriz", "Vsetín", "Vsetin", "Šumperk", "Sumperk", "Uherské Hradiště",
    "Uherske Hradiste", "Uherský Brod", "Hodonín", "Hodonin", "Břeclav", "Breclav",
    "Nové Město na Moravě", "Nove Mesto na Morave", "Dobrá Voda", "Dobra Voda",
    "Stružná", "Struzna", "Bocanovice", "Český Těšín", "Cesky Tesin", "Kolín", "Kolin",
  ],
  SK: [
    "Bratislava", "Košice", "Kosice", "Prešov", "Presov", "Žilina", "Zilina", "Nitra",
    "Banská Bystrica", "Banska Bystrica", "Trnava", "Trenčín", "Trencin", "Martin",
    "Poprad", "Prievidza", "Zvolen", "Považská Bystrica", "Povazska Bystrica",
    "Michalovce", "Spišská Nová Ves", "Spisska Nova Ves", "Komárno", "Komarno",
    "Levice", "Humenné", "Humenne", "Bardejov", "Liptovský Mikuláš", "Liptovsky Mikulas",
    "Ružomberok", "Ruzomberok", "Piešťany", "Piestany", "Topolčany", "Topolcany",
    "Čadca", "Cadca", "Dunajská Streda", "Dunajska Streda", "Rimavská Sobota",
    "Lučenec", "Lucenec", "Stará Ľubovňa", "Stara Lubovna", "Malacky",
    "Turčianske Kľačany", "Turcianske Klacany", "Okoč", "Okoc", "Opatovský Sokolec",
    "Opatovsky Sokolec", "Pezinok", "Senec", "Galanta", "Hlohovec", "Nové Zámky",
    "Nove Zamky", "Partizánske", "Partizanske", "Púchov", "Puchov", "Dolný Kubín",
    "Dolny Kubin", "Brezno", "Snina", "Skalica", "Senica", "Myjava", "Ilava",
    "Turčianske Teplice",
  ],
  AT: [
    "Wien", "Vienna", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt", "Villach",
    "Wels", "Sankt Pölten", "St. Pölten", "Dornbirn", "Wiener Neustadt", "Steyr",
    "Feldkirch", "Bregenz", "Leonding", "Klosterneuburg", "Baden", "Wolfsberg",
    "Lannach", "Leoben", "Krems", "Traun", "Amstetten", "Kapfenberg", "Hallein",
  ],
  BE: [
    "Brussel", "Bruxelles", "Brussels", "Antwerpen", "Antwerp", "Gent", "Ghent",
    "Charleroi", "Liège", "Liege", "Brugge", "Bruges", "Namur", "Leuven", "Mons",
    "Aalst", "Mechelen", "Hasselt", "Kortrijk", "Oostende", "Ostend", "Tournai",
    "Genk", "Seraing", "Roeselare", "Verviers", "Mouscron", "Beveren", "Dendermonde",
    "Turnhout", "Beringen", "Vilvoorde", "Lokeren", "Sint-Niklaas", "Ottignies",
    "Halle",
  ],
  NO: [
    "Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Fredrikstad",
    "Kristiansand", "Sandnes", "Tromsø", "Tromso", "Sarpsborg", "Skien", "Ålesund",
    "Alesund", "Sandefjord", "Haugesund", "Tønsberg", "Tonsberg", "Moss", "Porsgrunn",
    "Bodø", "Bodo", "Arendal", "Hamar", "Larvik", "Halden", "Lillehammer",
  ],
  NL: [
    "Amsterdam", "Rotterdam", "Den Haag", "The Hague", "Utrecht", "Eindhoven",
    "Groningen", "Tilburg", "Almere", "Breda", "Nijmegen", "Apeldoorn", "Haarlem",
    "Arnhem", "Enschede", "Amersfoort", "Hoorn", "Ede", "Maastricht", "Leiden",
    "Dordrecht", "Zoetermeer", "Zwolle", "Deventer", "Delft", "Heerlen", "Venlo",
    "Hilversum", "Hengelo", "Amstelveen", "Purmerend", "Schiedam", "Helmond",
    "Alkmaar", "Leeuwarden", "Roosendaal", "Vlaardingen", "Gouda",
    "Alphen", "Spijkenisse", "Westland", "Haarlemmermeer",
  ],
  LT: [
    "Vilnius", "Kaunas", "Klaipėda", "Klaipeda", "Šiauliai", "Siauliai", "Panevėžys",
    "Panevezys", "Alytus", "Marijampolė", "Marijampole", "Mažeikiai", "Mazeikiai",
    "Jonava", "Utena", "Kėdainiai", "Kedainiai", "Telšiai", "Telsiai", "Tauragė",
    "Taurage", "Ukmergė", "Ukmerge", "Visaginas", "Palanga", "Linkaučiai", "Linkauciai",
  ],
  IE: [
    "Dublin", "Cork", "Galway", "Limerick", "Waterford", "Drogheda", "Dundalk",
    "Swords", "Bray", "Navan", "Kilkenny", "Ennis", "Carlow", "Tralee", "Newbridge",
    "Portlaoise", "Balbriggan", "Naas", "Athlone", "Mullingar", "Wexford",
    "Letterkenny", "Sligo", "Clonmel", "Greystones", "Ballyboggan",
  ],
  HU: [
    "Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs", "Pecs", "Győr", "Gyor",
    "Nyíregyháza", "Nyiregyhaza", "Kecskemét", "Kecskemet", "Székesfehérvár",
    "Szombathely", "Szolnok", "Tatabánya", "Kaposvár", "Érd", "Veszprém", "Békéscsaba",
  ],
  CH: [
    "Zürich", "Zurich", "Genève", "Geneve", "Geneva", "Basel", "Bern", "Lausanne",
    "Winterthur", "Luzern", "Lucerne", "St. Gallen", "Sankt Gallen", "Lugano",
    "Biel", "Thun", "Köniz", "Koniz", "La Chaux-de-Fonds", "Schaffhausen", "Fribourg",
    "Chur", "Neuchâtel", "Neuchatel", "Uster", "Sion", "Vernier", "Baden",
  ],
  DK: [
    "København", "Kobenhavn", "Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg",
    "Randers", "Kolding", "Horsens", "Vejle", "Roskilde", "Herning", "Silkeborg",
    "Næstved", "Naestved", "Fredericia", "Viborg", "Køge", "Koge", "Holstebro",
  ],
  GB: [
    "London", "Manchester", "Birmingham", "Glasgow", "Edinburgh", "Liverpool",
    "Leeds", "Bristol", "Sheffield", "Newcastle", "Cardiff", "Belfast", "Leicester",
    "Nottingham", "Southampton", "Brighton", "Portsmouth", "Coventry", "Hull",
    "Bradford", "Stoke", "Wolverhampton", "Plymouth", "Derby", "Swansea", "Aberdeen",
  ],
  FR: [
    "Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg",
    "Montpellier", "Bordeaux", "Lille", "Rennes", "Reims", "Le Havre", "Saint-Étienne",
    "Toulon", "Grenoble", "Dijon", "Angers", "Nîmes", "Nimes", "Villeurbanne",
  ],
  IT: [
    "Roma", "Rome", "Milano", "Milan", "Napoli", "Naples", "Torino", "Turin",
    "Palermo", "Genova", "Genoa", "Bologna", "Firenze", "Florence", "Bari", "Catania",
    "Venezia", "Venice", "Verona", "Messina", "Padova", "Padua", "Trieste", "Brescia",
  ],
  ES: [
    "Madrid", "Barcelona", "Valencia", "Sevilla", "Seville", "Zaragoza", "Málaga",
    "Malaga", "Murcia", "Palma", "Las Palmas", "Bilbao", "Alicante", "Córdoba",
    "Cordoba", "Valladolid", "Vigo", "Gijón", "Gijon", "Granada", "A Coruña",
  ],
  UA: [
    "Kyiv", "Kiev", "Kijów", "Lviv", "Lwów", "Lvov", "Odesa", "Odessa", "Kharkiv",
    "Charków", "Dnipro", "Zaporizhzhia", "Vinnytsia", "Ivano-Frankivsk", "Ternopil",
    "Lutsk", "Łuck", "Rivne", "Równe", "Chernivtsi", "Uzhhorod", "Użhorod",
  ],
  SE: [
    "Stockholm", "Göteborg", "Goteborg", "Gothenburg", "Malmö", "Malmo", "Uppsala",
    "Västerås", "Vasteras", "Örebro", "Orebro", "Linköping", "Linkoping", "Helsingborg",
    "Jönköping", "Jonkoping", "Norrköping", "Norrkoping", "Lund", "Umeå", "Umea",
  ],
  FI: [
    "Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku", "Jyväskylä", "Jyvaskyla",
    "Lahti", "Kuopio", "Pori", "Kouvola", "Joensuu", "Lappeenranta",
  ],
  PT: [
    "Lisboa", "Lisbon", "Porto", "Vila Nova de Gaia", "Amadora", "Braga", "Funchal",
    "Coimbra", "Setúbal", "Setubal", "Almada", "Agualva-Cacém", "Queluz", "Faro",
  ],
  LV: [
    "Rīga", "Riga", "Daugavpils", "Liepāja", "Liepaja", "Jelgava", "Jūrmala", "Jurmala",
    "Ventspils", "Rēzekne", "Rezekne",
  ],
  EE: [
    "Tallinn", "Tartu", "Narva", "Pärnu", "Parnu", "Kohtla-Järve", "Viljandi",
  ],
  RO: [
    "București", "Bucuresti", "Bucharest", "Cluj-Napoca", "Timișoara", "Timisoara",
    "Iași", "Iasi", "Constanța", "Constanta", "Craiova", "Brașov", "Brasov", "Galați",
    "Galati", "Ploiești", "Ploiesti", "Oradea", "Brăila", "Arad", "Pitești",
  ],
};

/** Krótkie nazwy: tylko pełne równe `adr_Miejscowosc`, nigdy „contains”. */
export const IVOCLAR_CITY_EXACT_ONLY = new Set(
  [
    "ede",
    "oslo",
    "cork",
    "bray",
    "gent",
    "wels",
    "bern",
    "chur",
    "sion",
    "kyiv",
    "kiev",
    "lviv",
    "most",
    "opava",
    "nitra",
    "levice",
    "martin",
    "munster",
    "alphen",
    "hoorn",
    "naas",
    "erd",
    "pecs",
    "gyor",
    "lund",
    "pori",
    "faro",
    "riga",
    "biel",
    "thun",
    "uster",
    "arad",
    "vigo",
    "bari",
    "nice",
    "lille",
    "dijon",
    "angers",
    "hull",
    "leeds",
    "derby",
    "hamm",
    "jena",
    "ulm",
    "kiel",
    "hagen",
    "marl",
    "gera",
    "hanau",
    "cheb",
    "tabor",
    "zlin",
    "elk",
    "pila",
    "lask",
  ].map((s) => s.normalize("NFD").replace(/\p{M}/gu, "").toLowerCase())
);
