/** Copy PL flag zakupów na prośbach. */
export const PROCUREMENT_REQUEST_FLAG_COPY = {
  overflowSectionRequest: "Prośba",
  overflowSectionFlag: "Flaga",
  overflowEdit: "Popraw dane",
  overflowSupplierDetails: "Szczegóły dostawcy",
  overflowCancelRequest: "Anuluj prośbę",
  overflowFlagActive: "teraz",
  /** Modal z opisem / wyborem pozycji — poniżej szybkich skrótów. */
  overflowSet: "Ustaw z opisem…",
  overflowChange: "Edytuj z opisem…",
  modalTitle: "Flaga prośby (zakupy)",
  modalTitleMulti: "Flaga dla wybranych pozycji",
  modalHint: "Widoczna tylko w panelu dziennym — handlowiec jej nie widzi.",
  noteLabel: "Opis (opcjonalnie)",
  notePlaceholder: "Np. czekamy na potwierdzenie KH, brak stocku u dostawcy…",
  save: "Zapisz",
  cancel: "Anuluj",
  clear: "Usuń flagę",
  applyAllConfirm: "Zastosuj do wszystkich pozycji w grupie",
  selectLines: "Wybierz pozycje",
  filterAll: "Wszystkie",
  filterNone: "Bez flagi",
  filterVacation: "Urlop",
  filterBarLabel: "Filtr",
  manageFlags: "Zarządzaj",
  manageModalTitle: "Flagi zakupów",
  manageModalHint:
    "Kolejność flag (↑↓) ustawia kolejność torów flag i która flaga wygrywa w grupie mieszanej. Tory systemowe (Do zamówienia, Urlop…) przestawiasz strzałkami na nagłówku toru.",
  manageAdd: "Dodaj flagę",
  manageLabelPlaceholder: "Nazwa flagi",
  manageDeactivate: "Dezaktywuj",
  manageActivate: "Aktywuj",
  manageDelete: "Usuń",
  manageMoveUp: "W górę",
  manageMoveDown: "W dół",
  manageInactiveSection: "Nieaktywne",
  manageInactiveCurrent:
    "Ta flaga jest nieaktywna — możesz zmienić opis albo wybrać aktywną.",
  orphanChipLabel: "Nieznana flaga",
  emptyFilterVacation: "Brak próśb u dostawców na urlopie.",
  vacationChip: "Urlop dostawcy",
  vacationChipShort: "Urlop",
  mixedChip: "Flagi",
  emptyChipTitle: "Brak flagi",
  flagNoteHint: "Ma opis",
  flagNoteExpand: "Rozwiń opis",
  flagNoteCollapse: "Zwiń opis",
} as const;
