import type { MyOrderLine, MyOrderRow } from "./my-order-presenter";

export function createTestMyOrderLine(overrides: Partial<MyOrderLine> = {}): MyOrderLine {
  return {
    id: "l1",
    product: "Produkt A",
    symbol: "SYM",
    subiektTwId: null,
    mikranCode: null,
    quantity: "2",
    quantityLabel: "2 szt.",
    progressLabel: null,
    stockStatus: "waiting",
    canAcknowledgePickup: false,
    canCancelBySales: false,
    salesCancelPhase: null,
    maxSalesCancelQuantity: null,
    defaultSalesCancelQuantity: null,
    canPartialSalesCancel: false,
    showSalesCancelRemainder: false,
    showSalesCancelSupplierQuick: false,
    salesCancelDeliveredQty: 0,
    salesCancelUndoRestore: {},
    clientName: null,
    clientKhId: null,
    requestNote: null,
    procurementCancelNote: null,
    isTeeth: false,
    lineAcknowledgeMode: "none",
    ...overrides,
  };
}

export function createTestMyOrderRow(overrides: Partial<MyOrderRow> = {}): MyOrderRow {
  return {
    id: "1",
    kind: "zamowienie",
    lineCount: 1,
    lines: [createTestMyOrderLine()],
    submittedLabel: "01.05",
    supplierName: "Dostawca",
    product: "Produkt A",
    symbol: "SYM",
    quantityLabel: "2 szt.",
    progressLabel: null,
    statusTitle: "Zamówione",
    statusDetail: null,
    timingLabel: null,
    badgeVariant: "info",
    rowColor: "#fff",
    orderIds: ["1"],
    acknowledgeMode: "none",
    pickupPendingCount: 0,
    pickupPendingIds: [],
    pickupTeethPendingIds: [],
    pickupShelfPendingIds: [],
    pickupReadyTotal: 0,
    pickupAcknowledgedCount: 0,
    canCancelBySales: false,
    salesCancelPhase: null,
    salesCancelOrderIds: [],
    cancelNoticeOrderIds: [],
    cancelledAckOrderIds: [],
    clientLabel: null,
    supplierId: "s",
    salesPersonId: "sp",
    requestKind: "zamowienie",
    canEditBySales: false,
    headline: "Zamówione — czekamy na dostawę",
    headlineTone: "info",
    subline: null,
    requestNote: null,
    procurementCancelNote: null,
    productLaneKind: "regular",
    submissionGroupId: null,
    ...overrides,
  };
}
